# @author haiyang.song
# @date 2018-11-6

version: '2'

services:
  couchdb1.icdoit.com:
    container_name: couchdb1.icdoit.com
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=couchdb
      - COUCHDB_PASSWORD=couchdb
    volumes:
      - /opt/chainData/couchdb/couchdb1:/opt/couchdb/data

  peer1.icdoit.com:
    container_name: peer1.icdoit.com
    image: hyperledger/fabric-peer
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer1.icdoit.com
      - CORE_PEER_ADDRESS=peer1.icdoit.com:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.icdoit.com:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.icdoit.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.icdoit.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1.icdoit.com:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=couchdb
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=couchdb
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    extra_hosts:
      - "orderer1.icdoit.com:10.0.0.23"
      - "orderer2.icdoit.com:10.0.0.24"
      - "peer1.icdoit.com:10.0.0.21"
      - "peer2.icdoit.com:10.0.0.22"
    volumes:
      - "/var/run/:/host/var/run/"
      - "/opt/chainData/peer/peer1:/var/hyperledger/production"
      - "../crypto-config/peerOrganizations/icdoit.com/peers/peer1.icdoit.com/msp:/etc/hyperledger/fabric/msp"
      - "../crypto-config/peerOrganizations/icdoit.com/peers/peer1.icdoit.com/tls:/etc/hyperledger/fabric/tls"
    ports:
      - "7051:7051"
      - "7052:7052"
      - "7053:7053"